[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# PWA and SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for PWA
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Service Worker caching
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Static assets caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Video assets
[[headers]]
  for = "*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 